services:
  api:
      build: .
      ports:
        - "4000:4000"
  db:
      image: postgres
      restart: always
      environment:
        POSTGRES_PASSWORD: info
  adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080
  
 